version: "3"
services:

  app:
    build:
      context: .
      dockerfile: ./docker/web/dev.Dockerfile
    image: digitalocean.com/php
    container_name: lara_calendar_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: lara_calendar_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/web/.user.ini/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

 #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mariadb
    container_name: lara_calendar_db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3308:3306
    volumes:
      - "dbdata:/var/lib/mysql/data"
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lara_calendar_phpmyadmin
    restart: unless-stopped
    links:
      - db
    ports:
      - 8182:80
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

