version: '3'

services:
  db:
    image: mariadb:latest
    container_name: lara_calendar_db
    restart: always
    tty: true
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: localevents
      MYSQL_ROOT_PASSWORD: pipsology
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test:  mysql --user=root --password=pipsology -e 'Design your own check script ' LastSchema

  app:
    build:
      context: .
      dockerfile: ./docker/web/dev.Dockerfile
    image: digitalocean.com/php
    container_name: lara_calendar_app
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: lara_calendar_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/web/.user.ini/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

 #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: lara_calendar_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lara_calendar_phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - 8182:80
    depends_on:
      - db
    environment:
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: 3306
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

